apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fake-shop
  name: fake-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-shop
  template:
    metadata:
      labels:
        app: fake-shop
    spec:
      containers:
      - image: williamclown/fake-shop:v1
        name: fake-shop
        ports:
        - containerPort: 5000
        
---

apiVersion: v1
kind: Service
metadata:
  name: fake-shop
spec:
  selector:
      app: fake-shop
  ports:
  -  port: 80
     targetPort: 5000
  type: NodePort