#Deployment do banco de dados Postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
espec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
      spec:
        containers:
          - name: postgre
            image: postgres:13.16
            ports: 
              - containerPort: 5432
            env:
              - name: POSTGRES_DB
                value: fakeshop
              - name: POSTGRES_USER
                value: fakeshop
              - name: POSTGRES_PASSWORD
                value: Pg1234  
---                                       

apiVersion: v1
kind: Service
metadata:
  name: fake-shop
spec:
  selector:
      app: fake-shop
  ports:
  -  port: 80
     targetPort: 5000
  type: LoadBalancer

---
#Deployment da aplicação web
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fake-shop
  name: fake-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-shop
  template:
    metadata:
      labels:
        app: fake-shop
    spec:
      containers:
      - image: williamclown/fake-shop:v1
        name: fake-shop
        ports:
          - containerPort: 5000
        env:
          - name: DB_HOST
            value: postgre
          - name: DB_USER
            value: fakeshop
          - name: DB_PASSWORD
            value: Pg1234
          - name: DB_NAME
            value: fakeshop
          - name: FLASK_APP
            value: index.py
